### ISSUE TITLE
Tutorial Notebook Problems

### ISSUE THREAD

**Issue by MikeHeiber** [LuisDavidCamacho/high-performance-pandas#2]
I am trying to test out your tutorial notebook, but I am having some issues.  I cloned your repo, and when I run the notebook out of the root directory, the path to the data directory is not correct.  This is fixed when I run the notebook out of the press directory , but then the images do not show up. Could you please test that the notebook is working and provide instructions for how to use it in case I am doing something incorrectly?

**Comment by LuisDavidCamacho** [comment]
Hello Mike. Thanks for you interest in this project. I sugest to run the jupyter notebook command in the root folder, that's what I do. Nevertheless, the issue could be due to the path to data and to images is relative to the notebooks folder. You may want to check the os.gecwd() location or set the os.chdir() to the notebook location, everything should work just fine.

In the other hand I've just added new resources so you can donwload all the uncompressed data and run a new no HTML notebook out of the box. 

Hope this new version works for you as well as the tips. I you have any futher issue, please don't hesitate to post it, it will be much apreciated.
